from data.recipes import process_recipes_data
from data.restaurants import process_restaurant_data
from data.user_reviews import process_user_reviews_data


# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass

import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


process_restaurant_data()
process_recipes_data()
process_user_reviews_data()
